[project]
name = "cs336"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gvsai9", email = "gummadellivenkatsai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "regex>=2026.9.10",
    "torch>=2.14.0",
]

[project.scripts]
cs336 = "cs336:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
